#!/usr/bin/env python3
"""Temauppgift (Tema 5) -- 729G46.

Exempel på slumpmässig layout-funktion. Layout-funktionen skickas som
argument när en instans av tema5.LayoutTester skapas.
"""

# Läs denna fil för att se hur gränssnittet skapats.
import tema5
import random


def largest_square_width(squares):
    """
    Hittar kvadraten med högsta bredd i listan squares och
    returnenrar bredden.
    """
    largest_square_width = 0
    for square in squares:
        if square.winfo_width() > largest_square_width:
            largest_square_width = square.winfo_width()
    return largest_square_width


def add_to_x(start_left, margin_x, lsw):
    """
    Returnerar ett värde som läggs till på x
    kordinaten för att skapa nästa kolumn.
    """
    if start_left:
        return margin_x + lsw
    return -(margin_x + lsw)


def add_to_y(start_top, margin_y, lsw):
    """
    Returnerar ett värde som läggs till på y
    för bestämma nästa plats i kolumnen.
    """
    if start_top:
        return margin_y + lsw
    return - (margin_y + lsw)


def column_layout(squares, frame_height, frame_width, start_left, start_top):
    """Placera ut kvadraterna i listan squares som kolumner."""
    margin_x = 10
    margin_y = 10
    lsw = largest_square_width(squares)
    # Om start_left är sant så placeras första kvadraten till vänster i
    # fönstret, annars placeras den till höger
    if start_left:
        current_x = margin_x
    else:
        current_x = frame_width - margin_x - lsw

    # Om start_top är sant placeras första kvadraten i toppen av fönstret,
    # annars placeras den vid botten
    if start_top:
        current_y = margin_y
    else:
        current_y = frame_height - margin_y - lsw

    # Placerar ut alla kvadrater i squares vid dess rätta positioner i kolumner
    for square in squares:
        padding = (lsw - square.winfo_width()) / 2

        # Kollar om kolumnen fyller hela fönstret och
        # skapar en ny kolumn om den gör det
        if start_top:
            if current_y + lsw + margin_y > frame_height:
                current_y = margin_y
                current_x += add_to_x(start_left, margin_x, lsw)
        else:
            if current_y - margin_y < 0:
                current_y = frame_height - margin_y - lsw
                current_x += add_to_x(start_left, margin_x, lsw)

        # Placerar ut kvadraten om den inte kommer utanför rutan
        if start_left:
            if current_x + lsw + margin_x < frame_width:
                square.place(x=current_x + padding, y=current_y + padding)
            else:
                break
        else:
            if current_x - margin_x > 0:
                square.place(x=current_x + padding, y=current_y + padding)
            else:
                break

        current_y += add_to_y(start_top, margin_y, lsw)


if __name__ == "__main__":
    # layoutfunktionen som anropas av knappen "Kör layoutfunktion" skickas med
    # som ett funktionsobjekt när vi skapar en instans av LayoutTester (GUI:t)
    layout_tester = tema5.LayoutTester(column_layout)
